name: Collect IPs and Save to Files
on:
  schedule:
    - cron: '0 */6 * * *' # 每小时的第30分钟执行一次，UTC时间
  workflow_dispatch: # 允许手动触发
permissions:
  contents: write
  actions: write
jobs:
  collect-ip-addresses:
    runs-on: ubuntu-latest
    steps:
      - name: Delete previous workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 3
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests ipaddress selenium webdriver-manager
      - name: Run IP collection script
        run: python autoip6.py
      - name: Commit and push results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update ip.txt and ipv6.txt [auto]"
          file_pattern: ip.txt ipv6.txt  # 空格分隔,防逗号误解析
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          disable_globbing: true  # 禁用glob扩展
          skip_dirty_check: true  # 允许无变化commit
          skip_fetch: true  # 加速
      - name: Post Set Python
        run: echo "Post-setup complete"
      - name: Post Check out repository
        run: echo "Post-checkout complete"
